### ISSUE TITLE
Add a reset all stats button on the report page

### ISSUE THREAD

**Issue by brendanheywood** [catalyst/moodle-tool_curlmanager#17]

**Comment by xuangui2018** [comment]
Hi Bredan, once reset button is clicked, do you want to delete all the records in mdl_tool_curlmanager table? 

Do you want to record who clicked on reset button and what time the reset button is clicked?

**Comment by brendanheywood** [comment]
Yes it can't hurt to emit a moodle event when it is reset, and yeah just wipe out the whole table

**Comment by xuangui2018** [comment]
Please see https://github.com/catalyst/moodle-tool_curlmanager/pull/19

**Comment by xuangui2018** [comment]
This has been resolved with PR#19
