### ISSUE TITLE
Have admin setting to purge old data

### ISSUE THREAD

**Issue by brendanheywood** [catalyst/moodle-tool_curlmanager#18]
* [ ] admin setting which is purge data not updated in X period
* [ ] cron task which deletes anything not updated

This will still keep very old data as long as it keeps getting touched

**Comment by xuangui2018** [comment]
HI Bredan, could you please explain a bit more on this issue? 

admin setting which is purge data not updated in X period - Is it just a setting for the user to tick to purge data? Do you need the user to be able to specify the date range?

**Comment by brendanheywood** [comment]
There will be a new admin_setting_configduration which is set to a duration, and the default might be 3 months

The cron job will then delete any records with a last modified older than 3 months ago. If the setting is 0 then it does nothing and keeps them forever

**Comment by xuangui2018** [comment]
Would a drop down menu in config would a good choice? If so, what are the options? 0, 3 months, 6 months, 1 year, 2 years?

**Comment by brendanheywood** [comment]
No! Use admin_setting_configduration, it does everything for you

**Comment by xuangui2018** [comment]
Please see PR https://github.com/catalyst/moodle-tool_curlmanager/pull/21

**Comment by xuangui2018** [comment]
Thanks Bredan. I have modified the query. Please check again.
