### ISSUE TITLE
store the last stacktrace in the record

### ISSUE THREAD

**Issue by brendanheywood** [catalyst/moodle-tool_curlmanager#25]
The stacktrace might be slightly different each time, eg if triggered via an event, but the event is trigger from many different pages. We often won't care about the lower part of the stacktrace just the top, so just update it each time

**Comment by brendanheywood** [comment]
This can likely replace the path column completely

**Comment by xuangui2018** [comment]
Please see PR: https://github.com/catalyst/moodle-tool_curlmanager/pull/27
