### ISSUE TITLE
Add admin settings for an allow list of domains

### ISSUE THREAD

**Issue by brendanheywood** [catalyst/moodle-tool_curlmanager#5]
* [x] add two new admin settings, a allow list which is identical to the deny list
* [x] add a checkbox which enables this which defaults off
* [x] if this list is not enabled then it does nothing and it behaves as core does right now
* [x] but if the list of present then by default ALL urls will be blocked unless they are in this list
* [x] in the report, show for each url or domain whether it was an explicit disallow, or an explicit allow. If the enable checklist is not on, then still show the explicit allows so we can use this as a test of which urls need decisions

**Comment by xuangui2018** [comment]
This has been complete with PR 12.
